name: CI/CD for Django Template

# Trigger workflow on push and pull requests to main branch
on:
  push:
    branches:
      - main  # Run on push to the 'main' branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the 'main' branch

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.13"]  # Specify Python version(s) to test
        os: [ubuntu-latest]       # Specify OS environment (Ubuntu in this case)

    runs-on: ${{ matrix.os }}

    services:
      db:
        image: postgres:15-alpine  # Use PostgreSQL 15 with Alpine base image
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      # Clone repository for access to codebase
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure Python environment with specified version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Set Environment Variables for Django and PostgreSQL
      - name: Set Environment Variables
        run: |
          echo "DB_ENGINE=django.db.backends.postgresql" >> .env
          echo "DB_NAME=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DB_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env

      # Cache UV Astral dependencies for faster builds
      - name: Cache UV Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-uv-

      # Install UV Astral to manage the project
      - name: Install UV Astral
        run: |
          python -m pip install --upgrade pip
          pip install uv

      # Create and Use Virtual Environment with UV Astral
      - name: Create and Use Virtual Environment
        run: |
          uv venv create
          uv venv use

      # Sync dependencies with uv.lock if it exists
      - name: Sync Dependencies with uv.lock
        if: ${{ inputs.fileExists('uv.lock') }}  # Optional, checks if uv.lock exists
        run: uv sync

      # Install Dependencies for Development
      - name: Install Development Dependencies
        run: uv pip install --requirement requirements-dev.txt

      # Run Pre-commit Hooks to Ensure Code Quality
      - name: Run Pre-commit Hooks
        run: uv run pre-commit run --all-files

      # Check Python Code Formatting with Black
      - name: Run Black (Check Mode)
        run: uv run black --check .

      # Perform Linting with Ruff
      - name: Run Ruff
        run: uv run ruff check .

      # Check Import Ordering with isort
      - name: Run isort (Check Mode)
        run: uv run isort --check-only .

      # Execute the Django Test Suite
      - name: Run Django Tests
        run: uv run pytest
