name: CI/CD for Django Template

# Trigger workflow on push and pull requests to main branch
on:
  push:
    branches:
      - main  # Run on push to the 'main' branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the 'main' branch

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    services:
      db:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432

    steps:
      # Clone repository for access to codebase
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure Python environment with specified version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Set Environment Variables
      - name: Set Environment Variables
        run: |
          echo "DB_ENGINE=django.db.backends.postgresql" >> .env
          echo "DB_NAME=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DB_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env

      # Cache UV Astral dependencies for faster builds
      - name: Cache UV Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-uv-

      # Set up project dependencies using UV Astral
      - name: Install UV Astral
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Create and Use Virtual Environment
        run: |
          uv venv create
          uv venv use

      - name: Install Dependencies
        run: uv pip install --requirements pyproject.toml

      # Run pre-commit hooks
      - name: Run Pre-commit Hooks
        run: uv precommit run --all-files

      # Check code formatting
      - name: Run Black (Check Mode)
        run: uv run black --check .

      # Run code linting
      - name: Run Ruff
        run: uv run ruff check .

      # Check import ordering
      - name: Run isort (Check Mode)
        run: uv run isort --check-only .

      # Execute Django test suite
      - name: Run Django Tests
        run: uv run pytest
